namespace: "mateothegreat"
name: "prometheus_push_gateway"
version: "0.0.1"
readme: "README.md"
authors:
  - "Matthew Davis (https://matthewdavis.io)"
description: "Prometheus push gateway."
license: ["MIT"]
license_file: "COPYING"
tags: ["prometheus", "pushgateway", "monitoring", "metrics"]
repository: "https://github.com/mateothegreat/prometheus-push-gateway.git"
homepage: "https://github.com/mateothegreat/prometheus-push-gateway"
issues: "https://github.com/mateothegreat/prometheus-push-gateway/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
